sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shashank0490/react-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
  - docker run -e CI=true shashank0490/react-test npm test

after_success:
  - docker build -t shashank021/multi-client ./complex/client
  - docker build -t shashank021/multi-nginx ./complex/nginx
  - docker build -t shashank021/multi-server ./complex/server
  - docker build -t shashank021/multi-worker ./complex/worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shashank021/multi-client
  - docker push shashank021/multi-nginx
  - docker push shashank021/multi-server
  - docker push shashank021/multi-worker

deploy
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-526790442740'
  bucket_path: 'docker_multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY     
