sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shashank0490/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shashank0490/react-test npm test

after_success:
  - docker build -t shashank0490/multi-client ./client
  - docker build -t shashank0490/multi-nginx ./nginx
  - docker build -t shashank0490/multi-server ./server
  - docker build -t shashank0490/multi-worker ./worker
# Login to docker-cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Pushing images to docker-hub
  - docker push shashank0490/multi-client
  - docker push shashank0490/multi-nginx
  - docker push shashank0490/multi-server
  - docker push shashank0490/multi-worker
  
